import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import { Header } from "@/components/shared/Header";
import { Footer } from "@/components/shared/Footer";

const Cedra4F = localFont({
  src: [
    {
      path:"../../public/fonts/Cedra4F-Regular.woff2",
      weight: "400"
    },
    {
      path:"../../public/fonts/Cedra4F-Light.woff2",
      weight: "300"
    },
    {
      path:"../../public/fonts/Cedra4F-UltraLight.woff2",
      weight: "200"
    },
    {
      path:"../../public/fonts/Cedra4F-Thin.woff2",
      weight: "100"
    },
  ]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Cedra4F.className} antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
